import Head from "next/head";
import Link from "next/link";
import MiFooter from "@/components/layout/footer/miFooter";
import MiHeader from "@/components/layout/header/miHeader";
import Saludo from "@/components/layout/header/saludo";
import MainContainer from "@/components/pages/css/main/mainContainer/mainContainer";

export default function Css() {
  return (
    <>
      <Head>
        <title>Css</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cssFav.webp" />
      </Head>
      <MiHeader />
      <Saludo titulo="Css" />

      <main>
        <MainContainer />
      </main>
      <br />
      <Link href="./">Home</Link>
      <br />
      <br />
      <Link
        href="https://developer.mozilla.org/es/docs/Web/CSS"
        target="_blank"
      >
        Pulsa para ver la documentación oficial de CSS
      </Link>
      <MiFooter />
    </>
  );
}
