import Head from "next/head";
import Link from "next/link";
import MiFooter from "@/components/layout/footer/miFooter";
import MiHeader from "@/components/layout/header/miHeader";
import CssList from "@/components/pages/css/main/cssList/cssList";
import Saludo from "@/components/layout/header/saludo";

export default function Css() {
  return (
    <>
      <Head>
        <title>Css</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cssFav.webp" />
      </Head>
      <MiHeader />
      <main className="cssMain">
        <Saludo titulo="Css" />
        <CssList />
      </main>
      <Link
        href="https://developer.mozilla.org/es/docs/Web/CSS"
        target="_blank"
      >
        <h3>Pulsa para ver la documentación oficial de CSS</h3>
      </Link>
      <Link href="./">Home</Link>
      <MiFooter />
    </>
  );
}
