import MiFooter from "@/components/layout/footer/miFooter";
import MiHeader from "@/components/layout/header/miHeader";
import Head from "next/head";
import Link from "next/link";

export default function HtmlTabla() {
  return (
    <>
      <Head>
        <title>Tabla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/htmlFav.png" />
      </Head>
      <MiHeader />
      <main>
        <table border={1}>
          <thead>
            <tr>
              <th>Título1</th>
              <th>Título2</th>
              <th>Título3</th>
              <th>Título4</th>
              <th>Título5</th>
              <th>Título6</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Dato</td>
              <td>Dato</td>
              <td>Dato</td>
              <td>Dato</td>
              <td>Dato</td>
              <td>Dato</td>
            </tr>
            <tr>
              <td>Dato</td>
              <td>Dato</td>
              <td>Dato</td>
              <td>Dato</td>
              <td>Dato</td>
              <td>Dato</td>
            </tr>
            <tr>
              <td>Dato</td>
              <td>Dato</td>
              <td>Dato</td>
              <td>Dato</td>
              <td>Dato</td>
              <td>Dato</td>
            </tr>
          </tbody>
        </table>
        <Link href="../">Home</Link> | <Link href="./">Back</Link>
      </main>
      <MiFooter />
    </>
  );
}
