import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";
import Welcome from "@/components/layout/main/welcome";
import MiFooter from "@/components/layout/footer/miFooter";
import MiHeader from "@/components/layout/header/miHeader";
import Saludo from "@/components/layout/header/saludo";

const inter = Inter({ subsets: ["latin"] });

export default function React() {
  return (
    <>
      <Head>
        <title>React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/reactFav.png" />
      </Head>
      <MiHeader />
      <main className={` ${inter.className}`}>
        <Saludo titulo="React" />
        <p>
          ReactJS es una de las librerías más populares de JavaScript para el
          desarrollo de aplicaciones móviles y web. Creada por Facebook, React
          contiene una colección de fragmentos de código JavaScript
          reutilizables utilizados para crear interfaces de usuario (UI)
          llamadas componentes.
        </p>
        <ul>
          <li>
            <Link href="/REACT/componente">Componente react</Link>
          </li>
          <li>
            <Link href="/REACT/hook">Hook react useState</Link>
          </li>
        </ul>
      </main>
      <Link href="https://react.dev/" target="_blank">
        <span>Pulsa para ver la documentación oficial de React</span>
      </Link>
      <Link href="./">Home</Link>
      <MiFooter />
    </>
  );
}
