import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import MiFooter from "@/components/layout/footer/miFooter";
import MiHeader from "@/components/layout/header/miHeader";

const inter = Inter({ subsets: ["latin"] });

export default function Angular() {
  return (
    <>
      <Head>
        <title>Angular</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/angularFav.png" />
      </Head>
      <MiHeader />
      <main className={` ${inter.className}`}>
        <Link href="https://www.angular.io/" target="_blank">
          <h3>Pulsa para ver la documentación oficial de Angular</h3>
        </Link>
        <Link href="./">Home</Link>
      </main>
      <MiFooter />
    </>
  );
}
