import Head from "next/head";
import Link from "next/link";
import MiFooter from "@/components/layout/footer/miFooter";
import MiHeader from "@/components/layout/header/miHeader";
import Saludo from "@/components/layout/header/saludo";

export default function Angular() {
  return (
    <>
      <Head>
        <title>Angular</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/angularFav.png" />
      </Head>
      <MiHeader />
      <main>
        <Saludo titulo="Angular" />
      </main>
      <Link href="https://www.angular.io/" target="_blank">
        <h3>Pulsa para ver la documentación oficial de Angular</h3>
      </Link>
      <Link href="./">Home</Link>
      <MiFooter />
    </>
  );
}
