import MiFooter from "@/components/layout/footer/miFooter";
import MiHeader from "@/components/layout/header/miHeader";
import Saludo from "@/components/layout/header/saludo";
import MiListaEtiquetas from "@/components/pages/html/main/miListaEtiquetas";
import Head from "next/head";
import Link from "next/link";

export default function Html() {
  return (
    <>
      <Head>
        <title>Html</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/htmlFav.png" />
      </Head>
      <MiHeader />
      <main>
        <Saludo titulo="HTML" />
        <MiListaEtiquetas />
      </main>
      <Link
        href="https://developer.mozilla.org/es/docs/Web/HTML"
        target="_blank"
      >
        <h3>Pulsa para ver la documentación oficial de html</h3>
      </Link>
      <Link href="./">Home</Link>
      <MiFooter />
    </>
  );
}
