import MiFooter from "@/components/layout/footer/miFooter";
import MiHeader from "@/components/layout/header/miHeader";
import Head from "next/head";
import Link from "next/link";

export default function HtmlParrafos() {
  return (
    <>
      <Head>
        <title>Parrafos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/htmlFav.png" />
      </Head>
      <MiHeader />
      <main>
        <h2>Esto es un párrafo:</h2>
        <p>
          Lo que yo te diga, esto es un párrafo &lt;p&gt;.<br></br>
          <br></br>
          Lorem, <time dateTime="20:00">20:00</time> ipsum dolor sit amet
          consectetur adipisicing elit. Dolorem exercitationem, dolore,{" "}
          <br></br> rerum doloribus veritatis voluptates corrupti rem, est
          sapiente soluta pariatur tenetur ab facilis sed ex ipsam. Blanditiis,
          nemo recusandae?
        </p>
        <Link href="../">Home</Link> | <Link href="./">Back</Link>
      </main>
      <MiFooter />
    </>
  );
}
