import Head from "next/head";
import MiHeader from "@/components/layout/header/miHeader";
import MiFooter from "@/components/layout/footer/miFooter";
import Welcome from "@/components/layout/main/welcome";

export default function Home() {
  return (
    <>
      <Head>
        <title>Documentacion front-end</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/frontFav.png" />
      </Head>

      <MiHeader />
      <main className="miMain">
        <Welcome />
      </main>
      <MiFooter />
    </>
  );
}
