import MiFooter from "@/components/layout/footer/miFooter";
import MiHeader from "@/components/layout/header/miHeader";
import NavBar from "@/components/layout/header/navBar";
import MiIFrame from "@/components/pages/html/main/miIframe";
import Head from "next/head";
import Link from "next/link";

export default function HtmliFrame() {
  return (
    <>
      <Head>
        <title>iFrame</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/htmlFav.png" />
      </Head>
      <MiHeader />
      <main>
        <MiIFrame />
      </main>
      <MiFooter />
    </>
  );
}
